GOV-75: mock api for batch summary and batch details
ankita10r/ph-ee-connector-mock-payemet-schema pull request #1
Opened 2023-06-16 09:43 UTC by arkadasfynarfin

[GOV-75](https://mifosforge.jira.com/browse/GOV-75)

2023-06-16 09:44 UTC, arkadasfynarfin commented
@fynmanoj Please review this PR.
CC: @avikganguly01

2023-07-26 08:13 UTC, arkadasfynarfin commented
Hi @fynmanoj ,
We need these changes for `bulk-connector-closedloop` to work since we are consuming mock API's of `mock-payment-schema` there.

2023-08-01 06:57 UTC, fynmanoj requested changes

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/api/BatchApi.java
> +    @GetMapping("/batch/summary")
I understand that these APis are copied from the Operations app, yet we need to update them based on the REST API standards.

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/BatchDTO.java
> +    private String batch_id;
Use Lombok to generate getter, setters and constructors

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/BatchDTO.java
> +    public BatchDTO(String batch_id, String request_id, Long total, Long ongoing, Long failed, Long successful, BigDecimal totalAmount, BigDecimal successfulAmount, BigDecimal pendingAmount, BigDecim
instead of adding two conductors, create two factory methods with a proper name.
here its difficult to understand the use case of these constructors

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/BatchDetailResponse.java
> +    public List<Transfer> getContent() {
Use lombok

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/PageableDTO.java
> +    public SortDTO getSort() {
useLombok

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/BatchDetailResponse.java
> +public class BatchDetailResponse {
do we already have these DTOs in the batch processor/ connector common?
if this is a duplicate can you add them to connector common instead?

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/SortDTO.java
> +    public SortDTO(boolean sorted, boolean unsorted, boolean empty) {
use lombok

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/schema/Transfer.java
> +    public String getId() {
use lombok

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/service/BatchServiceImpl.java
> +        for(int i=0; i<10; i++){
variable name should be more descriptive than 'i'

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/service/BatchServiceImpl.java
> +        batchDTO.setBatch_id(batchId);
batch DTO already has couple of constructors added, why do we need to set the params individually?

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/service/BatchServiceImpl.java
> +                "39f6ac4d052e-72aa3ea4-e6f6-4880-877f", "a27631f6-6dd4-4d69-b4fc-8932bd721913",
are these hard-coded for mocking?

2023-08-01 06:57 UTC, fynmanoj commented on src/main/java/org/mifos/connector/mockPaymentSchema/service/BatchServiceImpl.java
> +        transfer.setId(String.valueOf(iteration));
use a factory method instead of setting each value separately

2023-08-01 06:57 UTC, fynmanoj commented on src/main/resources/application.yml
> +  server-port: 500
port is usually 4 digits for easy understanding.

2023-08-07 09:59 UTC, closed without merging